---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: nhc
      vars:
        yum_repositories_pkgs:
          - https://github.com/openhpc/ohpc/releases/download/v1.3.GA/ohpc-release-1.3-1.el7.x86_64.rpm
